title: setlust.com
email:
description: >- # 
  personal setlist connection. contact me directly for a PDF of any setlist.
twitter_username: jonthebastard
github_username: jonthebastard
minimal_mistakes_skin: dark
search: true

markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

permalink: /:categories/:title/
paginate: 8
paginate_path: /page:num/
timezone: America/Los_Angeles

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "jonathan pirro"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "I collect setlists. it's a problem."
  links:
    - label: "that guy with the mohawk"
      icon: "fas fa-fw fa-link"
      url: "https://www.thaguywiththemohawk.com/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/jonthebastard"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jonthebastard"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/jonthebastard"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/jonthebastard"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jonthebastard"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/jonthebastard"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
